name: DDPM   
steps: 100
schedule_cfg:
  beta: [0.0001, 0.01]
  beta_schedule: 'linear'
  s: 0.008
opt_interval: 1 # 
rand_t_type: 'half' # 'half' or 'all'
loss_type: 'l2' # 'l1' or 'l2'
use_all_pra_2: true

# consistency_model
sigma_data: 0.5
sigma_max: 80.0
sigma_min: 0.002
distillation: true
weight_schedule: uniform
loss_norm: l2
rho: 7.0
timesteps: 100
ema_rate: '0.999,0.9999,0.9999432189950708'
target_ema: 0.95
num_inference_steps: 4
optimizer: true
# consistency_model

sample:
  name: 'consistency_model' # 'dpmsolver+' / 'consistency_model' / 'DDPM' / 'short_cut'
  steps: 20 # The total number of function evaluations (NFE), i.e., the number of time steps in the sampling process
  order: 2 # The order of the sampling algorithm, 1 refers to DDIM, 2 means dpmsolver++ uses second-order sampling，3 means dpmsolver++ uses third-order sampling
  skip_type: 'time_uniform' # The type for the spacing of the time steps. 'time_uniform' or 'logSNR' or 'time_quadratic'.
  t_start: 1  # dpmsolver++ only supports inputs in continuous time, this sets the starting time for sampling at t = 1
  t_end: 0.01  # The end time for sampling, near 0, representing the terminal state of the diffusion process
  method: 'multistep'    #The method for sampling. 'singlestep' or 'multistep' or 'singlestep_fixed' or 'adaptive'.
